### PR TITLE
Add Edit link and useNavigate hook

### PR DESCRIPTION
**Pull request by Craftsman8**
# The newly added features are:

* Add Edit button to each BlogDetails component
* Implement handleDelete using axios.delete in BlogDetails.js
* Implement handleSubmit using 'POST' method in Create.js to add new component to the Server
*  Add useNavigate hook to route back to homepage after each Submit and Delete process
* Add styles to each button

### CODE REVIEW

**Review by Bestbynature — CHANGES_REQUESTED** [review]
Hello @Craftsman8, You have done a really beautiful job with your form submission and delete features.

However, if you check the console, you will notice an error. I have helped to figure out the source. 

in your Home component, you would need to remove line 7, 11 and 13. They are not needed at all as we are only interested in getting all the blogs in the home component.

**Once you do that, the error should disappear. Then resubmit for confirmation.**

**Comment by Craftsman8** [comment]
Sir, when I removed those lines, there was an error from line 17 and 19 where I set conditional loading whenever home is launched, saying; loading not definedand when I restore it, it also shows 'id' not defined.

so I only removed /${id} from the URL in line 13 and deleted lines 7 and 9.... and it worked

**Comment by Bestbynature** [comment]
Hi @Craftsman8, I can see the error that is causing the behaviour you described but I don't want to stress you further. Kudos and a good job done so far.

Kindly use @Bestbynature next time you leave comment so I can be notified by mail.

**Comment by Craftsman8** [comment]
@Bestbynature
Thank you sir,
And sir, my dev branch is only showing in my VScode terminal not on GitHub
What could have caused it sir

**Review by Bestbynature — APPROVED** [review]
joker-approved

approved


# Approved

**Comment by Bestbynature** [comment]
> @Bestbynature Thank you sir, And sir, my dev branch is only showing in my VScode terminal not on GitHub What could have caused it sir

do git push from your dev branch in vs code

> @Bestbynature Thank you sir, And sir, my dev branch is only showing in my VScode terminal not on GitHub What could have caused it sir

Hello @Craftsman8, It simply means you have not created the dev branch. That means you skipped the lesson. and the exercise.  so after you have merged this AddFormPage1, create a dev branch from the main branch before doing the next one and make it the default branch.

For hints on how to make a branch the default branch, kindly ask your colleagues or you look for the video we did.

 If you don't do the above, there is going to be issues later and it can be a serious one.

**Comment by Craftsman8** [comment]
@Bestbynature 
Yes 🤦 I'm not sure I've pushed from the branch
But I have it created before
I'll probably delete that and create new one

**Pull request merged**
